### ISSUE TITLE
CMakeLists.txt has hardcoded location

### ISSUE THREAD

**Issue by Beyond-Veil** [rgrosset/pico-pwm-audio#3]
Hi, thanks for your example file for the PWM audio and supporting files. this has been a great help so far

1 minor snafu: your CMakeLists.txt file has your SDK location hardcoded, preventing cmake from running for everyone without a user called robin ;) . A quick '#' solved the issue

It was a quick and easy fix for myself, but might catch some newer users trying to build the software

Finally, you propose the clone git@github link for downloading the repository. I would recommend changing that to the https://github version as otherwise the clone command will fail for users without an account on most clean build environments.

**Comment by rgrosset** [comment]
Thanks for this. I fixed those two issues just now. Appreciate the feedback!
